# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d7be9db1095bbceab2fa16e59c4511fa0a010da48c36971d69b4bb7a9b9ea759f1d13de5f89cac0d42c09678a58e87ed63cbef2ea720b5c9014ee300c1e2bac

test:
  secret_key_base: e5c1da32414d89d7dabe1724a76e32d291f6921fa5249adb96fba2407dedce1672db942e5f6c72c2afc1992c5e9728abf170b87e17e8347c976440139305f487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
